### ISSUE TITLE
Onboard Contraptions Don't Render With Shaders Enabled

### ISSUE THREAD

**Issue by 19PHOBOSS98** [ValkyrienSkies/Clockwork#23]
~ 0:37
https://youtu.be/p9z6Tt_r3y4

The Shaders I tested it on:
BSL_v8.2.01
ComplementaryShaders_v4.6
Sildur's+Vibrant+Shaders+v1.50+Lite

I found out while rendering a video with the Replay Mod

But it didn't render as well on normal single player mode... :(

**Comment by ThePlasticPotato** [comment]
Ruby fixed this apparently, at least with create tile entities, so- Job done!
